name: Main checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux-main-checks:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test-linux64
  macos:
    # https://github.com/actions/virtual-environments#available-environments
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test-mac64
